### PR TITLE
✨ Add ability to set MSW worker start options

### PR DESCRIPTION
**Pull request by deshiknaves**
There is currently no way to set worker start options. Export an optional `setMswWorkerOptions` function that will enable the end user to set the worker options.

Change `support/index.js` to:

```javascript
import { setMswWorkerOptions } from '../../src/support'

setMswWorkerOptions({ quiet: true, onUnhandledRequest: 'bypass' })
```

This PR also:
- Upgrades packages
- Fixes an issue where MSW would warn about unhandled requests
- Increases Cypress version to 11

### CODE REVIEW

**Comment by deshiknaves** [comment]
@raphaeleidus would you be able to take this for a spin?

**Comment by jameskraus** [comment]
@deshiknaves, I don't think these changes were ever published to npm

**Comment by deshiknaves** [comment]
Yep. Looks like the CircleCI image needs replacing. I'll have a look this evening.

**Comment by triglian** [comment]
@deshiknaves hello, I would also like these changes to setup the `url` property for the `serviceWorker` option. Let me know if I can do something to help.

**Comment by deshiknaves** [comment]
@triglian @jameskraus this has now been published. Sorry for the delay.

**Pull request merged**
